---
openapi: 3.0.0
info:
   version: 1.3.0
   title: ibmnew4 open api specification
   description: ibmnew4 API
   termsOfService: http://api_url/terms/
   contact:
      name: ContactName
      email: hello@wolox.co
      url: https://www.wolox.com.ar/
   license:
      name: Apache 2.0
      url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
   - url: http://localhost:8006
     description: ibmnew4
tags:
- name: ibm
paths:
   "/ibm":
      post:
         tags:
         -  ibm
         description: GpCreate
         requestBody:
            content:
               application/json:
                  schema:
                     $ref: "#/components/schemas/ibm"
         responses:
            200:
               description: Success
            400:
               description: Bad Request
            404:
               description: Not Found
            500:
               description: Internal Server Error
components:
   schemas:
      ibm:
         type: object
         properties:
            name:
               type: "string"
               description: Description